### PR TITLE
Tidy up es6 syntax for changeColor and adjust binding for invocation

### PR DESCRIPTION
**Pull request by tankwan**
Adjust binding in line 50 and tidy up class function definition in es6 for changeColor (line 19 and 24), otherwise gulp build rejects syntax

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! Probably good idea to not try to use fancy ES6+ features in a boilerplate.

**Comment by tankwan** [comment]
Hey Kevin!

Yeah there was just some issue with the compiling over at my end--I was
using gulp/browserify and it wasn't working.

I put together Pellets <https://pellets.herokuapp.com/>, a to-do list using
aframe-react and material-ui during a 2-day hack! Check it out if you are
any interested--comments are welcome!

Cheers,
Tony

**Comment by ngokevin** [comment]
Cool, Tony! I recommend using https://github.com/bryik/aframe-bmfont-text-component for better performance on the text. Or do geometry merging, but that's a bit more complex.

**Comment by tankwan** [comment]
Thanks so much Kevin! Hope your week's going great so far. -Tony

**Pull request merged**
